# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m
  go: "1.21"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errcheck
    - gosec
    - misspell

  disable:
    - lll  # Line length limit, can be re-enabled later after code formatting
    - wsl 
    - gomnd  # Magic number checks, too strict for tests and constants
    - gocyclo  # Cyclomatic complexity, too strict for existing code
    - goconst  # String constants, too strict for test strings
    - dupl  # Duplicate code detection, too strict for existing code
    - unparam  # Unused parameters, too strict for interface implementations
    - revive  # Too many style warnings for existing code
    - prealloc  # Pre-allocation suggestions, too strict
    - structcheck  
    - varcheck  
    - deadcode  

linters-settings:
  staticcheck:
    go: "1.21"
  
  gosec:
    excludes:
      - G404  # Disable weak random number generator check for test files

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
        - gosec
    - path: benchmarks_test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
        - gosec
    - path: torture_test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0 